# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spokane Broadband Initiative
email: spokane-broadband-initiative@googlegroups.com
description: >
  We're citizens of Spokane, Washington, exploring ways to increase broadband
  competition so that high-speed Internet is available, reliable, and
  affordable citywide.
baseurl: ""
url: "https://spokane-broadband-initiative.github.io"
#twitter_username: jekyllrb
github_username:  spokane-broadband-initiative

# Build settings
markdown: kramdown
